### ISSUE TITLE
Default super admin password

### ISSUE THREAD

**Issue by BrunoDonk** [csersoft/HWFW_GUI#11]
Hello how are you? Sorry my english, I'm from Brazil, I have a small internet provider, and I'm looking for a way to change the super administrator password of the Huwaei ONT via firmware to continue even after resetting, is it possible with this program? I don't know if I'm on the right path

**Comment by csersoft** [comment]
This program only provides firmware modification. If you want to modify the default administrator password, you need to unpack the exported rootfs, then modify the relevant files, and then repackage the rootfs and import it into the firmware.
