### ISSUE TITLE
请问如何解包和打包保存好的uimg？

### ISSUE THREAD

**Issue by qq57240** [csersoft/HWFW_GUI#2]
作者这个工具很强大，不过我的逆向水平很低，有这个工具也不会很好的使用。现在大概知道保存的uimg应该就是SquashFS镜像格式。
保存好rootfs的uimg结构，我把这个uimg文件放进ubuntu里通过unsquashfs可以解包出来，但用mksquashfs打包后有10m之多，再用您这个工具导入重新打包的文件就提示过大了。
我查看了用kmsquashfs打包的文件，头部16进制字节前4个字节和导出的uimg是两两相反的，也就是说魔法字不一样。
现在请求作者能教我如何正常重新打包文件为uimg。

**Comment by csersoft** [comment]
目前工作忙，暂时没有时间研究这个了，
建议自行调试跟踪下我这个工具的功能与流程，目前还存在很多bug，是当初设计时的问题。
或者clone 1.0.6版本编译下，我记得1.0.6有修复关于uimg的bug，不清楚可否解决你的问题。

**Comment by qq57240** [comment]
@csersoft 
大兄弟，我的hg8240已经砖了。。。
解包uimg后替换了busybox，然后再打包，再导入uimg，检查效验什么的都没问题我就刷了。
结果。。。。现在砖了，连ttl线，电脑显示无法识别的usb设备。。。。
我这情况还有救么？

**Comment by csersoft** [comment]
有救，只要硬件没坏，就有救。不过救砖难度很大，非专业的不容易救砖。

**Comment by csersoft** [comment]
> 连ttl线，电脑显示无法识别的usb设备
这个是你ttl小板驱动没装对，跟设备无关。

**Comment by qq57240** [comment]
@csersoft 
谢谢大兄弟提醒，我脑子坏了，用鼠标的usb线做了个线，上面都没2302芯片。。。
我这个情况不知道用ttl能不能恢复

**Comment by csersoft** [comment]
如果flash数据损坏，系统进不去，或者更早的loader坏了，光靠ttl是不行的。
要jtag配合ttl，不够过程也非常繁琐。需要一定的专业知识和动手能力。

**Comment by qq57240** [comment]
我看在看雪上有你用jtag修砖的过程，我把设备先买好，到时有不懂的还得请教你，真的感谢。

**Comment by csersoft** [comment]
我不一定有时间。你可以加这个群看看：212496900。

**Comment by alivelimeli** [comment]
How can I join the group @csersoft , @qq57240 ?

**Comment by csersoft** [comment]
It's Tencent QQ group. @alivelimeli
