### ISSUE TITLE
Not Working for Huawei Firmware

### ISSUE THREAD

**Issue by alivelimeli** [csersoft/HWFW_GUI#3]
Hello @csersoft ,

I'm trying to identify a Huawei modem firmware binary using binwalk but it doesn't recognize it as jiffs, squash etc. Also HWFW_GUI cannot show contents of the firmware.

```
$ binwalk -v Huawei.bin 

Scan Time:     2018-01-22 21:34:10
Target File:   /media/data/tmp/Huawei.bin
MD5 Checksum:  e1ddf1d896631b07331b5188d5b31ca2
Signatures:    344

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
4992299       0x4C2D2B        MySQL ISAM index file Version 1
```

It's definitely not MySQL ISAM index file :)

Here is the file:
 
[Huawei.bin.zip](https://github.com/ReFirmLabs/binwalk/files/1653158/Huawei.bin.zip)

HWFW_GUI cannot extract or show the contents of the firmware.

What is the problem and how can I solve it?

**Comment by csersoft** [comment]
I have not seen this data format, looks like it has been compressed.
This is not a format supported by HWFW_GUI.
